<a href="https://colab.research.google.com/github/danielrodriguez007/Data_Analysis/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
torch.__version__

'2.0.1+cu118'

In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensor
### Create Scalar,Vector,Matrix and Tensor
Read the documentation :  https://pytorch.org/docs/stable/tensors.html

In [3]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [5]:
MATRIX = torch.tensor([[7,9],
                       [9,7]])
print(MATRIX)

tensor([[7, 9],
        [9, 7]])


In [6]:
MATRIX.shape

torch.Size([2, 2])

In [7]:
print(MATRIX[0],MATRIX[1])

tensor([7, 9]) tensor([9, 7])


In [8]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [9]:
print(TENSOR.shape)

torch.Size([1, 3, 3])


## Random Tensor

We need random tensor becuase to many neural networks uses a large quantity of numbers and with random tensors we can look the results of the neural network and fit to get better results.

Random Tensor Documentation : https://pytorch.org/docs/stable/generated/torch.rand.html

In [10]:
random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.0479, 0.7164, 0.1302, 0.0804],
        [0.2842, 0.3294, 0.0608, 0.2748],
        [0.0756, 0.2911, 0.5900, 0.5517]])


In [11]:
print(random_tensor.shape)

torch.Size([3, 4])


In [12]:
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors and tensors like

In [14]:
#Use torch.arange 
one_to_ten = torch.arange(start=0,end=1050,step=50)
one_to_ten

tensor([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,  550,
         600,  650,  700,  750,  800,  850,  900,  950, 1000])

In [15]:
# Creating tensor with torch.like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
random_tensor_1 = torch.rand(3,4)

In [17]:
# Details of the tensor
print(random_tensor_1,'\n')
print(f"Datatype of the tensor: {random_tensor_1.dtype}")
print(f"Shape of the tensor: {random_tensor_1.shape}")
print(f"Device tensor is on: {random_tensor_1.device}")

tensor([[0.1953, 0.7135, 0.8941, 0.6744],
        [0.3472, 0.3008, 0.9996, 0.3200],
        [0.0757, 0.1820, 0.6499, 0.4504]]) 

Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensors

## Tensor operations include:


*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix Multiplication





In [18]:
#Addition
tensor = torch.tensor([1,2,3])
tensor.add(10)

tensor([11, 12, 13])

In [19]:
#Substration
tensor.sub(11)

tensor([-10,  -9,  -8])

In [20]:
#Multiplication
tensor.multiply(10)

tensor([10, 20, 30])

## Matrix multiplication

There are two main ways to multiplication of matrix in neural networks and deep learning:

*   Element-wise multiplication
*   Matrix Multiplication(dot product)

Source: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

*   The **inner dimensions** must match
*   The resulting matrix has the shape of the **outer dimensions**





In [21]:
# Element-wise multiplication
print(tensor,'*',tensor)
print(f"Result : {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Result : tensor([1, 4, 9])


In [22]:
# Matrix Multiplication
torch.matmul(tensor,tensor) 

tensor(14)

In [23]:
print(len(tensor))

3


In [24]:
%%time
torch.matmul(tensor,tensor) 

CPU times: user 72 µs, sys: 12 µs, total: 84 µs
Wall time: 88.9 µs


tensor(14)

In [25]:
tensor_a = torch.rand([3,2])
tensor_b = torch.rand([3,2])

In [26]:
# TRANSPOSE switches the axes or dimensions of a given tensor
print(tensor_b,tensor_b.shape,'\n')
print(tensor_b.T,tensor_b.T.shape)

tensor([[0.4864, 0.6894],
        [0.4146, 0.6597],
        [0.2112, 0.0481]]) torch.Size([3, 2]) 

tensor([[0.4864, 0.4146, 0.2112],
        [0.6894, 0.6597, 0.0481]]) torch.Size([2, 3])


In [27]:
torch.mm(tensor_a,tensor_b.T).shape

torch.Size([3, 3])

## Finding the min, max, mean, sum etc...(Tensor Aggregation)

In [33]:
# Create a Tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [34]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [36]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [37]:
# Find the mean - note the torch.mean() function requires a tensor float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [38]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [39]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
x.argmin()

tensor(0)

In [41]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsquezing tensors


*   Reshaping - reshaoes an input tensor to a defined shape
*   View - Return a view of an input tensor of certain shape but  
keep the same memory as the original tensor
*   Stacking - combine multiple tensors of the top of each others (vstack) or side by side (hstack)
*   Squeeze - removes all 1 dimension to a target tensor
*   Unsqueeze - add a 1 dimension to a target tensor
*   Permute - Return a view of the input with dimensions permuted (swapped) in a certain way







In [42]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [45]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])