<a href="https://colab.research.google.com/github/danielrodriguez007/Data_Analysis/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
torch.__version__

'2.0.1+cu118'

In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensor
### Create Scalar,Vector,Matrix and Tensor
Read the documentation :  https://pytorch.org/docs/stable/tensors.html

In [3]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [5]:
MATRIX = torch.tensor([[7,9],
                       [9,7]])
print(MATRIX)

tensor([[7, 9],
        [9, 7]])


In [6]:
MATRIX.shape

torch.Size([2, 2])

In [7]:
print(MATRIX[0],MATRIX[1])

tensor([7, 9]) tensor([9, 7])


In [8]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [9]:
print(TENSOR.shape)

torch.Size([1, 3, 3])


## Random Tensor

We need random tensor becuase to many neural networks uses a large quantity of numbers and with random tensors we can look the results of the neural network and fit to get better results.

Random Tensor Documentation : https://pytorch.org/docs/stable/generated/torch.rand.html

In [10]:
random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.5919, 0.2365, 0.0546, 0.1767],
        [0.3507, 0.3666, 0.3590, 0.1052],
        [0.5987, 0.7062, 0.2657, 0.5484]])


In [11]:
print(random_tensor.shape)

torch.Size([3, 4])


In [12]:
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors and tensors like

In [19]:
#Use torch.arange 
one_to_ten = torch.arange(start=0,end=1050,step=50)
one_to_ten

tensor([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,  550,
         600,  650,  700,  750,  800,  850,  900,  950, 1000])

In [20]:
# Creating tensor with torch.like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
random_tensor_1 = torch.rand(3,4)

In [26]:
# Details of the tensor
print(random_tensor_1,'\n')
print(f"Datatype of the tensor: {random_tensor_1.dtype}")
print(f"Shape of the tensor: {random_tensor_1.shape}")
print(f"Device tensor is on: {random_tensor_1.device}")

tensor([[0.1523, 0.7945, 0.4897, 0.8485],
        [0.3140, 0.8581, 0.6346, 0.5789],
        [0.0947, 0.9227, 0.2758, 0.4761]]) 

Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensors

## Tensor operations include:


*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix Multiplication





In [27]:
#Addition
tensor = torch.tensor([1,2,3])
tensor.add(10)

tensor([11, 12, 13])

In [29]:
#Substration
tensor.sub(11)

tensor([-10,  -9,  -8])

In [30]:
#Multiplication
tensor.multiply(10)

tensor([10, 20, 30])

## Matrix multiplication

There are two main ways to multiplication of matrix in nueral networks and deep learning:

*   Element-wise multiplication
*   Matrix Multiplication(dot product)

Source: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

*   The **inner dimensions** must match
*   The resulting matrix has the shape of the **outer dimensions**





In [33]:
# Element-wise multiplication
print(tensor,'*',tensor)
print(f"Result : {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Result : tensor([1, 4, 9])


In [34]:
# Matrix Multiplication
torch.matmul(tensor,tensor) 

tensor(14)

In [36]:
print(len(tensor))

3


In [37]:
%%time
torch.matmul(tensor,tensor) 

CPU times: user 666 µs, sys: 38 µs, total: 704 µs
Wall time: 497 µs


tensor(14)

In [47]:
tensor_a = torch.rand([3,2])
tensor_b = torch.rand([3,2])

In [48]:
# TRANSPOSE switches the axes or dimensions of a given tensor
print(tensor_b,tensor_b.shape,'\n')
print(tensor_b.T,tensor_b.T.shape)

tensor([[0.8597, 0.8309],
        [0.4298, 0.8391],
        [0.2034, 0.9118]]) torch.Size([3, 2]) 

tensor([[0.8597, 0.4298, 0.2034],
        [0.8309, 0.8391, 0.9118]]) torch.Size([2, 3])


In [50]:
torch.mm(tensor_a,tensor_b.T).shape

torch.Size([3, 3])