<a href="https://colab.research.google.com/github/danielrodriguez007/Data_Analysis/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
torch.__version__

'2.0.1+cu118'

In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensor
### Create Scalar,Vector,Matrix and Tensor
Read the documentation :  https://pytorch.org/docs/stable/tensors.html

In [ ]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [ ]:
MATRIX = torch.tensor([[7,9],
                       [9,7]])
print(MATRIX)

tensor([[7, 9],
        [9, 7]])


In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
print(MATRIX[0],MATRIX[1])

tensor([7, 9]) tensor([9, 7])


In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
print(TENSOR.shape)

torch.Size([1, 3, 3])


## Random Tensor

We need random tensor becuase to many neural networks uses a large quantity of numbers and with random tensors we can look the results of the neural network and fit to get better results.

Random Tensor Documentation : https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.4123, 0.3036, 0.8763, 0.5675],
        [0.3154, 0.6442, 0.5951, 0.8306],
        [0.2092, 0.4384, 0.1911, 0.8841]])


In [ ]:
print(random_tensor.shape)

torch.Size([3, 4])


In [ ]:
zeros = torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])