<a href="https://colab.research.google.com/github/danielrodriguez007/Data_Analysis/blob/main/Student_Grades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive 
drive.mount ('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd 
from sklearn.linear_model import LinearRegression 
from sklearn.utils import shuffle 

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv')
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [4]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]] 
predict = "G3" 
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])  

from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


In [5]:
linear_regression = LinearRegression() 
linear_regression.fit(xtrain, ytrain) 
accuracy = linear_regression.score(xtest, ytest) 
print(accuracy)

0.8143423113995811


In [6]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])
  

[[12.83498201 10.6528173  15.6421554  -1.60087818 10.6528173 ]
 [12.83498201 12.83498201 15.6421554  -1.60087818  6.45543923]
 [ 9.4514196   7.99216755 15.6421554   8.02939124  9.65342631]
 ...
 [ 9.65342631  7.99216755 -0.63411515  8.02939124  8.02939124]
 [ 9.60117491  3.98006406 -0.63411515 -1.60087818 -1.60087818]
 [ 7.99216755  7.28785462 -0.63411515 -1.60087818 12.83498201]] [[[11 13  1  1 10]
  [10 11  2  0  6]
  [16 15  2  0 11]
  [ 4  0  1  2  0]
  [10 11  2  0  6]]

 [[11 13  1  1 10]
  [11 13  1  1 10]
  [16 15  2  0 11]
  [ 4  0  1  2  0]
  [ 8  7  2  0  6]]

 [[ 9 10  2  0  4]
  [10  8  1  0  6]
  [16 15  2  0 11]
  [ 7  9  1  1  2]
  [10 10  2  1 14]]

 ...

 [[10 10  2  1 14]
  [10  8  1  0  6]
  [ 6  0  1  0  0]
  [ 7  9  1  1  2]
  [ 7  9  1  1  2]]

 [[10 10  2  0  4]
  [ 5  5  2  0  4]
  [ 6  0  1  0  0]
  [ 4  0  1  2  0]
  [ 4  0  1  2  0]]

 [[10  8  1  0  6]
  [ 5  9  2  2  6]
  [ 6  0  1  0  0]
  [ 4  0  1  2  0]
  [11 13  1  1 10]]] [array([[13, 11, 15,  0, 11]