<a href="https://colab.research.google.com/github/danielrodriguez007/Data_Analysis/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf 
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.8.2


In [3]:
mnist = tf.keras.datasets.mnist 

(x_train, y_train), (x_test, y_test) = mnist.load_data() 
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.15334143, -0.6146556 , -0.25070235,  0.36333132,  0.20573066,
        -0.72345895,  0.3069257 , -0.29947647,  0.05979474, -0.7264436 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.12558825, 0.05826559, 0.08384459, 0.15493391, 0.13234313,
        0.0522588 , 0.14643668, 0.07985327, 0.11437266, 0.05210307]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.951547

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3016 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1450 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1092 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0879 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0769 - accuracy: 0.9758


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0742 - accuracy: 0.9776 - 492ms/epoch - 2ms/step


[0.07418668270111084, 0.9775999784469604]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.5220587e-07, 2.0729926e-08, 6.3286898e-05, 1.6692554e-04,
        4.8286597e-11, 1.6134077e-08, 9.8918520e-14, 9.9965012e-01,
        6.7929562e-07, 1.1830305e-04],
       [1.7080942e-09, 6.8639261e-03, 9.9312073e-01, 1.4701530e-05,
        5.2594734e-17, 3.2124873e-07, 5.8169604e-08, 2.7855884e-12,
        2.5441093e-07, 3.5535048e-15],
       [2.3720496e-08, 9.9927586e-01, 7.6458593e-05, 4.4670073e-06,
        2.3227334e-05, 1.2020678e-06, 1.4169683e-06, 6.0307217e-04,
        1.4236169e-05, 8.8577409e-08],
       [9.9975151e-01, 1.9532969e-08, 1.5231426e-04, 9.1491451e-08,
        2.3679802e-07, 2.1814336e-07, 4.1332354e-05, 9.7583479e-06,
        1.9233550e-08, 4.4467350e-05],
       [4.9018938e-05, 2.1147914e-08, 3.6870999e-05, 7.5539305e-07,
        9.9078989e-01, 3.9693751e-07, 2.2999224e-05, 6.4007362e-04,
        1.0687052e-06, 8.4588965e-03]], dtype=float32)>